export const books = [
    {
                id: 1,
                title: "ඒත් මං ආදරෙයි | Eth Man Adarei",
                author: "Abdul Umar Sahan Nethmina",
                genre: "Poetry",
                year: "Unknown",
                rating: 6.8,
                category: "Teens",
                pages: 100,
                location: "MLC/P/0001/TN",
                description: "කවදාහරි දාවසකදි මේ මගුල් කියවලා ඔයාටත් හිතුනොතින් මම පිස්සෙකැයි කියා අද වගෙම එදාටත් තියම් කවියක ලියා පිස්සෙකුගේ ආදරේ තාම දන්නෑ ඔයා ",
                image: "https://katha.lk/wp-content/uploads/2024/06/s0251-eth-man-aadarei-abdul-umar-sahan-nethmina.webp",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 2,
                title: "ඉතිං මට සමාවෙන්න | Ithin Mata Samawenna",
                author: "Abdul Umar Sahan Nethmina",
                genre: "Poetry",
                year: "Unknown",
                rating: 6.9,
                category: "Teens",
                pages: 62,
                location: "MLC/P/00002/TN",
                description: "බැරිම හින්දා කවමදාවත් ආයෙ ඔබ වෙත හැරෙන්න කිසිත් කියන්න බෑ ඉතිං මට, “සමා වෙනු මැන!” ඇරෙන්න ජීවිතේ තව බොහෝ දුර ඇති අතරමග බෑ මැරෙන්න ඔබත් ඔහොමම මගදි හමුවන වංගුවක් ළඟ හැරෙන්න",
                image: "https://katha.lk/wp-content/uploads/2024/11/s0504-ithin-mata-samawenna-abdul-umar-sahan-nethmina.webp",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 3,
                title: "ඒ දවස් හරි වෙනස් | E Dawas Hari Wenas",
                author: "Abdul Umar Sahan Nethmina",
                genre: "Novel",
                year: "Unknown",
                rating: 8.8,
                category: "YA",
                pages: 494,
                location: "MLC/N/0003/YA",
                description: "ඉස්සෙල්ලා ම ඔහුට ඇයගෙ හීනි ඇඟිලි තුඩුවල ස්පර්ශය දැනෙන්න ගත්තා. ඒත් එක්ක ම ඇඟිලිවලින් පටං ගත්ත උණුසුමක් මුලු ඇඟ පුරා ම පැතිරෙන විදිහ ඔහුට දැණුනා. ඇගේ අත සිනිඳු වුණා වගේ ම උණුසුම් වුණා. ඒක ඔහුට ඇති කරේ ගුලිවෙලා නිදාගැනීමේ වුවමනාවක්. මූට මේ මොකක් ද වුණේ වගේ ලුක් එකක් එක්ක ඇය ඔහු දිහාවට හැරුණා. මුකුත් නොකිය ම ඔහුත් ඇය දිහා බලාගෙන ඉඳලා තිබුණා. තත්පර දහයක් විතර ඔවුන් එකිනෙකා දිහා බලාගෙන ඉද්දි, ඔහුට ඇත්තට ම හැමදේම හොඳින් සිද්ධවෙයි කියලා දැනෙන්න පටං ගත්තා. ඒ වගේ ම හැමදේම හොඳින් සිද්ධ වේවි කියලා ඔහු විශ්වාස කරන්න පටං අරගෙන තිබුණා. ඒත් එක්ක ම කඳවුරේ කෙළවරකින් කවුදෝ කෑගහනවා ඇහුණා. “සිරිමල් අයියා වැටිලා…”",
                image: "https://katha.lk/wp-content/uploads/2025/06/S0526-E-Dawas-Hari-Wenas-Abdul-Umar-Sahan-Nethmina.webp",
                available: true,
                status: "leaving" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 4,
                title: "අබ්දුල් වෙන්න කලින් | Abdul Wenna Kalin",
                author: "Abdul Umar Sahan Nethmina",
                genre: "Poetry",
                year: "Unknown",
                rating: 4.9,
                category: "Teens",
                pages: 80,
                location: "MLC/P/00004/TN",
                description: "අපිට පස්සෙන් පියාඹන උං ආයෙ හිරවිය යුතුද කොටුවල තටු කපපු දුක අපි වගේ උං ආයෙමත් ලිය යුතුද පිටුවල ගොරව ගොරවා බලං ඉන්නවා තමයි වටේම අඳුරු කරුවල එහෙව් විටකදි ගින්දරක් මිස එලිය මදි දුර ඈත තරුවල",
                image: "https://katha.lk/wp-content/uploads/2025/11/S0575-Abdul-Wnna-Kalin-Abdul-Umar-Sahan-Nethmina.webp",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 5,
                title: "ආකිමිඩිස් සිය දිවි නසා ගනී | Akimidis Siya Diwi Nasa Gani",
                author: "Ruuso",
                genre: "Poetry",
                year: "2022 NOV",
                rating: 7.0,
                category: "Teens",
                pages: 80,
                location: "MLC/P/00005/TN",
                description: "එකපාරම මහ හයියෙන් වහින්න ගත්තා කරදරයි නම් තමයි ඒත් මං වහලෙ තෙමෙන තැන් දැනගත්තා",
                image: "https://rasakatha.lk/wp-content/uploads/2024/09/WhatsApp-Image-2024-09-15-at-8.03.23-AM-548x800.jpeg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 6,
                title: "අම්මපයි මං කඩුව දුන්නා | Ammapayi Man Kaduwa Dunna",
                author: "Shashika Sadeep",
                genre: "Poetry",
                year: "Unknown",
                rating: 7.2,
                category: "Teens",
                pages: 86,
                location: "MLC/P/00006/TN",
                description: "සැඩ සුළඟ දරන්නට නොහැකි තැන රුවලට මග කියපු තරු කැටත් පැන ගියපු රැයකට සයුර මැද මාලිගා කටු කැඩුණු නැවකට ප්‍රේමයකි, ප්‍රදීපාගාරයක එළි වැට",
                image: "https://rasakatha.lk/wp-content/uploads/2024/01/69-1.jpg",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 7,
                title: "කැමෙලියා | Camellia",
                author: "Virajini Thennakoo",
                genre: "Novel",
                year: "Unknown",
                rating: 5.8,
                category: "Teens",
                pages: 222,
                location: "MLC/N/00007/TN",
                description: "“බල්ලො මිනිස්සු වගේ කතා කරන්න පුරුදු වුණා නම් උන් ඔච්චර හොඳ වෙන්නෙ නෑ කියලත් මතක තියාගන්න. එහෙනං උන් ඔයාව හපා කන්නෙ වලිගෙ වනලා” -ඇනිටා",
                image: "https://katha.lk/wp-content/uploads/2024/06/s0300-camellia-virajini-thennakoon.webp",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 8,
                title: "රෝජා | Roja",
                author: "Niluka Brandon",
                genre: "Romance",
                year: "Unknown",
                rating: 4.2,
                category: "YA",
                pages: 392,
                location: "MLC/R/00008/YA",
                description: "මිනිස්සු… දුබලයන්ව ඉපදෙන්නාහ. මිනිස්සු… ජීවිතයේ යම් යම් යුගවල විවිධ හේතු කාරණාවන් නිසාවෙන් දුබලයන්ව ජීවිතය රැකගන්නාහ. නමුත්… අප කිසිවෙකුටත් දුබලයන්ව මිය යන්නට අයිතියක් නැත. අපි නැඟිටිය යුතුය! අපි හිනැහිය යුතුමය!",
                image: "https://katha.lk/wp-content/uploads/2024/06/s0296-roja-niluka-brandon.webp",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 9,
                title: "ඇත්ත කියපන් ක්ලියෝපැට්‍රා | Atta Kiyapan Cleopatra",
                author: "Bebadu Kumara",
                genre: "Poetry",
                year: "Unknown",
                rating: 8.6,
                category: "Teens",
                pages: "error 101",
                location: "MLC/P/00009/TN",
                description: "ප්‍රේමයේ ඉරිතැළුම් වලට සොයාගෙන නෑ සැත්කම් නමුදු සදහට නුඹේ නමටයි මේ පපුවේ වත්කම් කාලයා විසින් විසඳාවි රිදුම් දෙන සංසාර ගෙත්තම් මම මක්කරන්නද අපිට අපි හිමි නැත්නම්... හිනාව තියෙන දුරකට ඔයා දුවගෙන යන්න මම බලාගෙන ඉන්නම්",
                image: "https://rasakatha.lk/wp-content/uploads/2024/07/WhatsApp-Image-2024-07-28-at-7.12.56-PM.jpeg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 10,
                title: "ප්‍රබන්ධ සම්බන්ධ | Fiction Affairs",
                author: "Sri Jayathilaka",
                genre: "Novel",
                year: "Unknown",
                rating: 7.6,
                category: "YA",
                pages: "error 101",
                location: "MLC/N/00010/YA",
                description: "Sorry, No description available.",
                image: "https://rasakatha.lk/wp-content/uploads/2025/05/WhatsApp-Image-2025-05-28-at-9.49.13-PM-430x687.jpeg",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 11,
                title: "London",
                author: "Edward Rutherfurd",
                genre: "Novel",
                year: "1997 JAN",
                rating: 8.9,
                category: "YA",
                pages: 1332,
                location: "MLC/N-E/00011/YA",
                description: "Here is Edward Rutherfurd’s classic novel of London, a glorious pageant spanning two thousand years. He brings this vibrant city’s long and noble history alive through the ever-shifting fortunes, fates, and intrigues of half-a-dozen families, from the age of Julius Caesar to the twentieth century. Generation after generation, these families embody the passion, struggle, wealth, and verve of the greatest city in the Old World",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1328313657i/12407442.jpg",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 12,
                title: "Forget Me Not | ෆොගෙට් මී නොට්",
                author: "Charitha Prawardhi Bandara | Chathuri Damayanthi",
                genre: "Novel",
                year: "Unknown",
                rating: 6.8,
                category: "Teens",
                pages: 226,
                location: "MLC/N/00012/TN",
                description: "බිඳුණු මිනිස්සුන්ට ආදරය කරන එක කොහෙත්ම ලේසි නෑ යුමී සං කැබලි වෙච්චි ඔවුන්ව තදින් වැළඳගත යුතු වෙනවා මුදු නමුත් ස්ථීර ප්‍රේමයකින්. ඒත් ඒ තියුණු දාර සහිත බිඳුණු කැබලි, වැළදගන්නා ආදරණීයයාව රිදවනවා. ඔහුවත් කපා දමනවා. මට හොඳටම විශ්වාසයි, ආදරය කියන්නේ කැපකිරීමක්” වග කියන්නට ඇත්තේ, මේ ලෝකයේ මුල් වතාවට බිඳුණු ගැහැණියකට ආදරය කරපු කරුණාවන්ත ඇහිපිය ඇති පිරිමියෙක්. කැබලි වුණු පිරිමියෙකුට ප්‍රේම කළ විශාල හදවතක් ඇති ගහැණියක්.",
                image: "https://katha.lk/wp-content/uploads/2024/05/s0185-forget-me-not-charitha-prawardhi-bandara-chathuri-damayanthi.webp",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 13,
                title: "ඇහැළ මලට දම් පාටක් | Ehela Malata Dam Patak",
                author: "Chathuri Damayanthi",
                genre: "Novel",
                year: "Unknown",
                rating: 7.5,
                category: "YA",
                pages: 290,
                location: "MLC/N/00013/YA",
                description: "Working on it.",
                image: "https://katha.lk/wp-content/uploads/2024/05/s0186-ehala-malata-dam-patak-chathuri-damayanthi.webp",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 14,
                title: "දවසක් දා හැන්දෑවක | Dawasak Da Handawaka",
                author: "Rasika Jayakody",
                genre: "Miscellaneous",
                year: "Unknown",
                rating: 6.0,
                category: "YA",
                pages: 120,
                location: "MLC/M/00014/YA",
                description: "ජීවිතයේ කෙළවරක් නැති මිනිස් සබඳතාවලටත් මේ ‘න්‍යාය’ ම ගළපන්නට පුළුවන්. කතාබහ කිරීම සහ කතා නොකර සිටීම, හමුවීම සහ හමු නොවී සිටීම, ළං වීම සහ දුරස්ව සිටීම, පැමිණීම සහ නොපැමිණීම…මේ සියල්ලක් ම ජීවත් වීම සඳහා අවශ්‍යයි. මේ සියලුම සංසිද්ධීන් එකකට එකක් වෙන් කළ නොහැකි සේ සහ සම්බන්ධයි. සංගීත සංධ්වනියක ස්වර සහ නිහැඬියාව වගේ… කවියක කියැවෙන දේ සහ නො කියැවෙන දේ වගේ. මා ජීවිතය කියවන විදියට ‘උපේක්ෂාව’ යනු මේ සහ සම්බන්ධය තේරුම් ගැනීමයි. උපේක්ෂාව එක්තරා විදියක සුවබර නිද්‍රාවක්.",
                image: "https://katha.lk/wp-content/uploads/2024/07/s0449-dawasak-da-handawaka-rasika-jayakody.webp",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 15,
                title: "If It's Not Forever",
                author: "Durjoy Datta | Nikita Singh",
                genre: "Romance",
                year: "2012",
                rating: 6.0,
                category: "Adult",
                pages: 239,
                location: "MLC/M/00015/A",
                description: "If It's Not Forever is a novel by Durjoy Datta and Nikita Singh.[1] It was published in the year 2012 by Grapevine India Publishers. It is set on the story of the 2011 Delhi High Court blasts.[2][3] Though mentioned as a love story, it is more of a suspense thriller. There are seven characters mentioned in this book, with the main protagonist being Debashish (Deb), who hails from Bengal and is deeply scarred with haunting memories of the blast. The book has received average reviews from critics all over India.",
                image: "https://upload.wikimedia.org/wikipedia/en/2/2a/If_Its_Not_Forever.jpg",
                available: false,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 16,
                title: "බයෝ කරපු ඒලෙවල් | Bio Karapu A Level",
                author: "Abdul Umar Sahan Nethmina",
                genre: "Poetry",
                year: "Unknown",
                rating: 5.4,
                category: "Teens",
                pages: 52,
                location: "MLC/P/00016/TN",
                description: "මට ඕනෙ දැං ඔයා එක්ක ස්නායුවක් දිගේ ගලන ආවේගයක් වෙන්න ඔයාට ඉස්සෙල්ලාම දුවන්න දීලා අල්ලන්න වගේ දුවගෙන එන්න අපිට ඒ ගමං පුලුවන් කංකාල පේෂියක සෛල වෙන්න කොයිතරම් දෙපැත්තට ඇදුණත් ඩෙස්මසෝම අල්ලං ඉන්න විදිහ ගැන කියවන්න අපේ ආදරෙත් ඒ වගේ නේද කියලා කොඳුරන්න ඉතිං ඉක්මනට කියන්න මට ඔයා එතවද නැද්ද යන්න",
                image: "https://katha.lk/wp-content/uploads/2024/04/s0153-bio-karapu-alevel-abdul-umar-sahan-nethmina.webp",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 17,
                title: "2001: A Space Odyssey",
                author: "Arthur C. Clarke",
                genre: "Sci-Fi",
                year: "1968 APR 28",
                rating: 9.4,
                category: "YA",
                pages: 297,
                location: "MLC/SFC/00017/YA",
                description: "On the Moon, an enigma is uncovered. So great are the implications of this discovery that for the first time men are sent out deep into our solar system.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1432468943i/70535.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 18,
                title: "2010: Odyssey Two",
                author: "Arthur C. Clarke",
                genre: "Sci-Fi",
                year: "1982 DEC 01",
                rating: 8.7,
                category: "YA",
                pages: 320,
                location: "MLC/SFC/00018/YA",
                description: "When 2001: A Space Odyssey first shocked, amazed, and delighted millions in the late 1960s, the novel was quickly recognized as a classic. Since then, its fame has grown steadily among the multitudes who have read the novel or seen the film based on it. Yet, along with almost universal acclaim, a host of questions has grown more insistent through the years.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1372677992i/18048525.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 19,
                title: "2061: Odyssey Three",
                author: "Arthur C. Clarke",
                genre: "Sci-Fi",
                year: "1987 DEC",
                rating: 8.6,
                category: "YA",
                pages: 266,
                location: "MLC/SFC/00019/YA",
                description: "The third book in Clarke’s beloved Space Odyssey continues the story of Heywood Floyd, survivor of two previous encounters with the mysterious monoliths and the alien intelligences behind them. Floyd is chosen as one of a handful of celebrity guests to witness the first manned touchdown on the surface of Halley’s Comet on the privately-owned spaceship Universe.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1397988971i/18126623.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 20,
                title: "3001: The Final Odyssey",
                author: "Arthur C. Clarke",
                genre: "Sci-Fi",
                year: "1999 JAN 01",
                rating: 8.9,
                category: "YA",
                pages: 188,
                location: "MLC/SFC/00020/YA",
                description: "On an ill-fated mission to Jupiter in 2001, the mutinous supercomputer HAL sent crewmembers David Bowman and Frank Poole into the frozen void of space. Bowman’s strange transformation into a Star Child is traced through the novels 2010 and 2061. But now, a thousand years after his death, Frank Poole is brought back to life—and thrust into a world far more technically advanced than the one he left behind.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1568155089l/53087570.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 21,
                title: "The Wolf's Curse",
                author: "Jessica Vitalis",
                genre: "Fiction",
                year: "2021 SEP 21",
                rating: 9.2,
                category: "YA",
                pages: 336,
                location: "MLC/FIC/00021/YA",
                description: "Twelve-year-old Gauge’s life has been cursed since the day he witnessed a Great White Wolf steal his grandpapá’s soul, preventing it from reaching the Sea-in-the-Sky and sailing into eternity. When the superstitious residents of Bouge-by-the-Sea accuse the boy of crying wolf, he joins forces with another orphan to prove his innocence. They navigate their shared grief in a journey that ultimately reveals life-changing truths about the wolf––and death.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1611847802i/56382404.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 22,
                title: "New Dragon City: Eine verbotene Freundschaft",
                author: "Mari Mancusi",
                genre: "Fantasy",
                year: "2022 OCT 04",
                rating: 9.3,
                category: "YA",
                pages: 339,
                location: "MLC/F/00022/YA",
                description: "No one predicted the dragon apocalypse. The dragons came suddenly and decimated the world as we knew it, including New York City. Now, three years later, Noah, his hardcore survivalist father, and a ragtag group of survivors are barely scraping by in this new reality. Kids scavenge not only for materials in abandoned homes but also for leftover books at the library. Adults spend their time establishing a make-shift society and defending their shelter... with any means available. At least for the few months the dragons are hibernating, until it’s no longer safe aboveground.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1706158553i/205902593.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 23,
                title: "Something Like Home",
                author: "Andrea Beatriz Arango",
                genre: "Poetry",
                year: "2023 SEP 12",
                rating: 9.3,
                category: "Teens",
                pages: 256,
                location: "MLC/P/00023/TN",
                description: "Laura Rodríguez Colón has a plan: no matter what the grown-ups say, she will live with her parents again. Can you blame her? It’s tough to make friends as the new kid at school. And while staying at her aunt’s house is okay, it just isn’t the same as being in her own space.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1679081550i/70916843.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 24,
                title: "An Academic Affair",
                author: "Jodi McAlister",
                genre: "Romance",
                year: "2025 NOV 11",
                rating: 6.4,
                category: "Adult",
                pages: 366,
                location: "MLC/R/00024/A",
                description: "Sadie Shaw and Jonah Fisher have been academic rivals since they first crossed paths as undergraduates in the literature department thirteen years ago. Now that a highly coveted teaching opportunity has come up, their rivalry hits epic proportions. Jonah needs the job to move closer to his recently divorced sister and her children, while Sadie needs the financial security and freedom of a full-time teaching position.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1743882229i/224003821.jpg",
                available: true,
                status: "new" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 25,
                title: "With You Forever",
                author: "Chloe Liese",
                genre: "Romance",
                year: "2021 SEP 14",
                rating: 9.0,
                category: "YA",
                pages: 384,
                location: "MLC/R/00025/YA",
                description: "Rooney Sullivan is sunshine incarnate and the antithesis of quiet, reserved Axel. He’s been able to hide his attraction to her until a party game gets out of hand and ends in an unexpected kiss. Months later, Rooney’s staying just next door to him for a cozy A-frame getaway and temptingly within reach.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1690944101i/195036925.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 26,
                title: "Black Sheep",
                author: "Wattney Lander",
                genre: "Poetry",
                year: "2019 SEP 07",
                rating: 7.6,
                category: "Teens",
                pages: 117,
                location: "MLC/P/00026/TN",
                description: "Black Sheep is a collection of poetry and prose inspired by an awakening that lead to discover the sickness within a herd, perfect for those who have broke free from the unhealthy dynamics of their family.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1677848265i/52141218.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 27,
                title: "Book Lovers",
                author: "Emily Henry",
                genre: "Romance",
                year: "2022 MAY 03",
                rating: 9.1,
                category: "YA",
                pages: 377,
                location: "MLC/R/00027/YA",
                description: "Nora Stephens’ life is books—she’s read them all—and she is not that type of heroine. Not the plucky one, not the laidback dream girl, and especially not the sweetheart. In fact, the only people Nora is a heroine for are her clients, for whom she lands enormous deals as a cutthroat literary agent, and her beloved little sister Libby.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1638867089i/58690308.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 28,
                title: "The Love Hypothesis",
                author: "Ali Hazelwood",
                genre: "Romance",
                year: "2021 SEP 14",
                rating: 8.7,
                category: "Adult",
                pages: 400,
                location: "MLC/R/00028/A",
                description: "As a third-year Ph.D. candidate, Olive Smith doesn't believe in lasting romantic relationships—but her best friend does, and that's what got her into this situation. Convincing Anh that Olive is dating and well on her way to a happily ever after was always going to take more than hand-wavy Jedi mind tricks: Scientists require proof. So, like any self-respecting biologist, Olive panics and kisses the first man she sees.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1747519081i/56732449.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 29,
                title: "The Lion, the Witch and the Wardrobe",
                author: "C.S. Lewis",
                genre: "Fantasy",
                year: "1950 OCT 16",
                rating: 7.0,
                category: "Children",
                pages: 180,
                location: "MLC/F/00029/C",
                description: "They open a door and enter a world NARNIA...the land beyond the wardrobe, the secret country known only to Peter, Susan, Edmund, and Lucy...the place where the adventure begins. Lucy is the first to find the secret of the wardrobe in the professor's mysterious old house. At first, no one believes her when she tells of her adventures in the land of Narnia. But soon Edmund and then Peter and Susan discover the Magic and meet Aslan, the Great Lion, for themselves. In the blink of an eye, their lives are changed forever.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1697079942i/132080146.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },

            {
                id: 30,
                title: "Prince Caspian",
                author: "C.S. Lewis",
                genre: "Fantasy",
                year: "1951 OCT 16",
                rating: 6.8,
                category: "Children",
                pages: 240,
                location: "MLC/F/00030/C",
                description: "A prince denied his rightful throne gathers an army in a desperate attempt to rid his land of a false king. But in the end, it is a battle of honor between two men alone that will decide the fate of an entire world.",
                image: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1308814880i/121749.jpg",
                available: true,
                status: "" // new arrival: new, Leaving soon: leaving, or null
            },
        ];
